# -----------------------------------------------------------------------------
# Koda Alacritty Colors
# Theme: Koda Dark
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#101010'
foreground = '#a8a8a8'

# Normal colors
[colors.normal]
black = '#101010'
red = '#ff5733'
green = '#86cd82'
yellow = '#d9ba73'
blue = '#b3b3b3'
magenta = '#f2a4db'
cyan = '#5abfb5'
white = '#a5adce'

# Bright colors
[colors.bright]
black = '#666666'
red = '#ff7676'
green = '#a3d6a3'
yellow = '#ffffff'
blue = '#666666'
magenta = '#f4b8e4'
cyan = '#fafafa'
white = '#b5bfe2'
