#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
show_hidden = true
ratio       = [ 0, 1, 0 ]
sort_by     = "natural"
sort_sensitive = false
sort_dir_first = true
scrolloff   = 3

[plugin]
fetchers = [
	{ id = "mime-dir",    url = "*/",         run = "mime.dir",    prio = "high", group = "mime" },
	{ id = "mime-local",  url = "local://*",  run = "mime.local",  prio = "high", group = "mime" },
	{ id = "mime-remote", url = "remote://*", run = "mime.remote", prio = "high", group = "mime" },
]
