# PATH

# Default path
export PATH="/opt/homebrew:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# rbenv
export PATH="$HOME/.rbenv/shims:$PATH"
# Allow any custom binaries
export PATH="$HOME/bin:$PATH"
# yarn
export PATH="$HOME/.yarn/bin:$PATH"
# Add gnu packages
export PATH="$(brew --prefix gnu-sed)/libexec/gnubin:$PATH"
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
export PATH="$(brew --prefix grep)/libexec/gnubin:$PATH"

export VOLTA_FEATURE_PNPM=1
# curl
export PATH="/opt/homebrew/curl/bin:$PATH"
# GO
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
# postgres
export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
# Cargo
export PATH="$HOME/.cargo/bin:$PATH"
# Python3
export PATH=/usr/local/opt/python/libexec/bin:$PATH

# php
export PATH="/opt/homebrew/opt/php@8.3/bin:$PATH"
export PATH="/opt/homebrew/opt/php@8.3/sbin:$PATH"

# znap
# https://github.com/marlonrichert/zsh-snap
# -------------------------------------------------
source ~/.znap/znap.zsh

# oh-my-zsh plugins
znap source ohmyzsh/ohmyzsh lib/theme-and-appearance
znap source ohmyzsh/ohmyzsh lib/clipboard
znap source ohmyzsh/ohmyzsh lib/completion
znap source ohmyzsh/ohmyzsh lib/key-bindings
znap source ohmyzsh/ohmyzsh lib/git
znap source ohmyzsh/ohmyzsh plugins/git
znap source ohmyzsh/ohmyzsh plugins/history
znap source ohmyzsh/ohmyzsh plugins/vi-mode
znap source ohmyzsh/ohmyzsh plugins/tmux

# zsh plugins
znap source hlissner/zsh-autopair
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap source zsh-users/zsh-completions

# https://github.com/rbenv/rbenv
znap eval rbenv 'rbenv init -'

# https://github.com/mroth/scmpuff
znap eval scmpuff 'scmpuff init -s --aliases=false'
znap eval direnv 'direnv hook zsh'
znap eval starship 'starship init zsh'
znap prompt

export VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
export VI_MODE_SET_CURSOR=true

# Load my dotfiles after
# -------------------------------------------------
for file in ~/.{extra,aliases,functions,work}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

if [ "$ALACRITTY" = "true" ]
then
  ln -sf $HOME/.config/nvim/plugged/tokyonight.nvim/extras/alacritty/tokyonight_moon.toml $HOME/.config/alacritty/active.toml
  export BAT_THEME="OneHalfDark"
fi

# Exports
# -------------------------------------------------

# Change 'z' alias for use with the fzf function
export ZSHZ_CMD="_z"

# Make nvim the default editor
export EDITOR="nvim"

# LESS
# Syntax highlighting
export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"
# Default flags used in all LESS instances
export LESS='--line-numbers --status-column --long-prompt --ignore-case --hilite-search --RAW-CONTROL-CHARS'

# Larger history (allow 32³ entries; default is 500)
export HISTSIZE=999999999
export HISTFILESIZE=$HISTSIZE
export SAVEHIST=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Shorter timeout when pressing ESC
export KEYTIMEOUT=1

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
# Homebrew will not send analytics
export HOMEBREW_NO_ANALYTICS=1
# Homebrew will not auto-update before running `brew install`, `brew upgrade` or `brew tap`.
export HOMEBREW_NO_AUTO_UPDATE=1

# Node dev
export NODE_ENV=development

# Stop z polluting the home dir
export _Z_DATA="$HOME/.zdata/.z"

# bat
# https://github.com/sharkdp/bat
export BAT_CONFIG_PATH="$HOME/.batconfig"

# nnn
# https://github.com/jarun/nnn
export NNN_OPTS="dHe"
export LC_COLLATE="C"

# fzf
# https://github.com/junegunn/fzf
# -------------------------------------------------

# Setting ag as the default source for fzf - include hidden files
export FZF_DEFAULT_COMMAND='ag --follow --hidden --ignore .git -g ""'
# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# Preview files when highlighting
export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
# Default options
export FZF_DEFAULT_OPTS="--multi --inline-info --height 40%"
# Use a split pane in tmux
export FZF_TMUX=1
export FZF_TMUX_HEIGHT=40%
# Shell integration
[ -s ~/.fzf.zsh ] && source ~/.fzf.zsh

# Enhance ALT-C with better sorting and a tree preview
# http://theinfiniteset.net/content/2016/08/combining-tools-blsd-and-fzf/
command -v blsd > /dev/null && export FZF_ALT_C_COMMAND='blsd'
command -v tree > /dev/null && export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -$LINES'"

bindkey '^o' autosuggest-accept

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
