# PATH

# Default path
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
# rbenv
export PATH="$HOME/.rbenv/shims:$PATH"
# Allow any custom binaries
export PATH="$HOME/bin:$PATH"
# yarn
export PATH="$HOME/.yarn/bin:$PATH"
# Add gnu packages
export PATH="$(brew --prefix gnu-sed)/libexec/gnubin:$PATH"
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
export PATH="$(brew --prefix grep)/libexec/gnubin:$PATH"

# GO
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

# Cargo
export PATH="$HOME/.cargo/bin:$PATH"

# Python3
export PATH=/usr/local/opt/python/libexec/bin:$PATH

# zplug

export ZPLUG_USE_CACHE=true
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "lib/theme-and-appearance", from:oh-my-zsh
zplug "lib/clipboard", from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh
zplug "lib/key-bindings", from:oh-my-zsh
zplug "lib/directories", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/tmux", from:oh-my-zsh
zplug "plugins/history", from:oh-my-zsh

zplug "hlissner/zsh-autopair", defer:3
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-completions", defer:2

zplug load

# Load my dotfiles after
for file in ~/.{extra,aliases,functions,work}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

# Exports

# Change 'z' alias for use with the fzf function
export ZSHZ_CMD="_z"

# Make nvim the default editor
export EDITOR="nvim"

# LESS
# Syntax highlighting
export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"
# Default flags used in all LESS instances
export LESS='--line-numbers --status-column --long-prompt --ignore-case --hilite-search --RAW-CONTROL-CHARS'

# Larger history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Shorter timeout when pressing ESC
export KEYTIMEOUT=1

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
# Homebrew will not send analytics
export HOMEBREW_NO_ANALYTICS=1
# Homebrew will not auto-update before running `brew install`, `brew upgrade` or `brew tap`.
export HOMEBREW_NO_AUTO_UPDATE=1

# Node dev
export NODE_ENV=development

# Stop z polluting the home dir
export _Z_DATA="$HOME/.zdata/.z"

# bat
# https://github.com/sharkdp/bat
export BAT_CONFIG_PATH="$HOME/.batconfig"

# nnn
# https://github.com/jarun/nnn

export NNN_OPTS="dHe"
export LC_COLLATE="C"

# fzf
# https://github.com/junegunn/fzf

# Setting ag as the default source for fzf - include hidden files
export FZF_DEFAULT_COMMAND='ag --follow --hidden --ignore .git -g ""'
# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# Preview files when highlighting
export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
# Default options
export FZF_DEFAULT_OPTS="--multi --inline-info --height 40%"
# Use a split pane in tmux
export FZF_TMUX=1
export FZF_TMUX_HEIGHT=40%
# Shell integration
[ -s ~/.fzf.zsh ] && source ~/.fzf.zsh

# Enhance ALT-C with better sorting and a tree preview
# http://theinfiniteset.net/content/2016/08/combining-tools-blsd-and-fzf/
command -v blsd > /dev/null && export FZF_ALT_C_COMMAND='blsd'
command -v tree > /dev/null && export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -$LINES'"

# volta
# https://docs.volta.sh/
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# https://starship.rs/
eval "$(starship init zsh)"

# https://github.com/rbenv/rbenv
eval "$(rbenv init -)"

# https://github.com/mroth/scmpuff
eval "$(scmpuff init -s --aliases=false)"

# https://github.com/direnv/direnv
eval "$(direnv hook zsh)"

bindkey '^o' autosuggest-accept

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
