version: "1.0"
defaults:
  # Base directory for worktrees (relative to project root)
  base_dir: "../worktrees"

hooks:
  post_create:
    # Copy AI context file from main worktree to new worktree
    - type: copy
      from: ".claude"
      to: ".claude"
