name: service
root: ~/wahanda/service
startup_window: nvim

windows:
  - nvim: nvim
  - zsh:
    - sdk use java 11.0.18-amzn
  - services:
      layout: even-horizontal
      panes:
        - asset:
            - cd ~/wahanda/service/asset/webapp
            - sdk use java 11.0.18-amzn
        - site:
            - cd ~/wahanda/service/site/webapp
            - sdk use java 11.0.18-amzn
  - watch:
      layout: even-horizontal
      panes:
        - asset:
          - cd ~/wahanda/service/asset/webapp
        - site:
          - cd ~/wahanda/service/site/webapp
  - rainbow:
    - cd ~/wahanda/service/rainbow
    - sdk use java 11.0.18-amzn
