name: service
root: ~/wahanda/service
startup_window: nvim

windows:
  - nvim: nvim
  - zsh:
    -
  - services:
      layout: even-horizontal
      panes:
        - asset:
            - cd ~/wahanda/service/asset/webapp
            - sdk use java 11.0.12.7.2-amzn
            - mvn spring-boot:run
        - site:
            - cd ~/wahanda/service/site/webapp
            - sdk use java 11.0.12.7.2-amzn
            - mvn spring-boot:run
  - watch:
      layout: even-horizontal
      panes:
        - asset:
          - cd ~/wahanda/service/asset/webapp
        - site:
          - cd ~/wahanda/service/site/webapp
  - rainbow:
    - cd ~/wahanda/service/rainbow
    - sdk use java 11.0.12.7.2-amzn
    - mvn spring-boot:run
